[features]
seeds = false
skip-lint = false
[programs.localnet]
hello_world_with_react = "7wZ5gGfuFLcambH1bTpXiPycANgVv1rM2QVUAdrEhRaq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/raashid/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
